### ISSUE TITLE
Virtual unit map plot still uses matplotlib

### ISSUE THREAD

**Issue by shashwatsridhar** [INM-6/swan#13]
The virtual unit map feature still uses matplotlib for plotting. For consistency and better compatibility with Qt signals and slots, we should switch to pyqtgraph.

**Comment by shashwatsridhar** [comment]
This might even be a nice issue for @kloss-o to take up, since it involves essentially replicating existing functionality and would be a good way to learn pyqtgraph, signals and slots, and the relationship between real units and virtual units. Thoughts @mdenker?

**Comment by mdenker** [comment]
Yes, true -- that's still a relic from the early days I think, and really, matplotlib doesn't make much sense here. Not sure if this would be a show-stopper for 1.0.0, but let's keep it on the radar!
