### ISSUE TITLE
Swan logo

### ISSUE THREAD

**Issue by JuliaSprenger** [INM-6/swan#14]
I think at some point swan should also get a logo. I just came across some old drafts of mine. Feel free to reuse in the future

![swan_logo](https://user-images.githubusercontent.com/8088860/105753974-c5294680-5f49-11eb-91f3-0f2402caa96a.png)
[swan_logo.svg](https://github.com/INM-6/swan/files/5869093/swan_logo.svg.txt)

**Comment by mdenker** [comment]
I think this is really a great draft. I'll pass it by SBC for guidance and feedback.

**Comment by shashwatsridhar** [comment]
Ah, fantastic, thank you @JuliaSprenger :D 
I agree with @mdenker, this a good draft!

Who/what is SBC, though?

**Comment by mdenker** [comment]
New logo is awaiting licensing, will make a PR soon.
