### ISSUE TITLE
Current author email address outdated

### ISSUE THREAD

**Issue by shashwatsridhar** [INM-6/swan#23]
The current author email address listed in the package metadata in `setup.py` is outdated. This should be updated to a current one. I'd be okay with listing my official gmail address, unless @mdenker you have preference in this regard.

**Comment by mdenker** [comment]
Sure, please go ahead. I think this should always reflect the current address of the best suited person to contact for a given release.  I'd leave it up to you -- If you prefer not to be listed, you can put my email.

**Comment by shashwatsridhar** [comment]
Alright, I'll go ahead and enter my email address! :)
